'use client';

import { Download, FileText, Check } from 'lucide-react';
import { useState } from 'react';
import { cn } from '@/lib/utils';

interface DownloadButtonProps {
  formula: {
    title: string;
    latex: string;
    explanation: string;
    history?: string | null;
    example: string;
    difficulty: string;
    category: {
      name: string;
    };
  };
}

export default function DownloadButton({ formula }: DownloadButtonProps) {
  const [isDownloading, setIsDownloading] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);

  const handleDownload = () => {
    setIsDownloading(true);
    
    // Create a beautifully formatted HTML summary
    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${formula.title} - Summary</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&family=Space+Grotesk:wght@700&display=swap');
          body { 
            font-family: 'Inter', sans-serif; 
            color: #1e293b; 
            line-height: 1.6; 
            padding: 40px; 
            max-width: 800px; 
            margin: 0 auto;
            background: #f8fafc;
          }
          .card {
            background: white;
            padding: 60px;
            border-radius: 40px;
            box-shadow: 0 20px 50px rgba(0,0,0,0.05);
            border: 1px solid #e2e8f0;
          }
          h1 { 
            font-family: 'Space Grotesk', sans-serif;
            font-size: 48px; 
            margin-bottom: 10px; 
            color: #0f172a;
            letter-spacing: -0.04em;
          }
          .badge {
            display: inline-block;
            padding: 6px 16px;
            background: #6366f1;
            color: white;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-bottom: 40px;
          }
          .formula-box {
            background: #0f172a;
            color: white;
            padding: 40px;
            border-radius: 24px;
            text-align: center;
            font-size: 32px;
            margin: 40px 0;
            font-family: serif;
          }
          h2 {
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.2em;
            color: #64748b;
            margin-top: 40px;
            margin-bottom: 16px;
            border-bottom: 2px solid #f1f5f9;
            padding-bottom: 8px;
          }
          p { margin-bottom: 24px; font-size: 18px; color: #475569; }
          .footer {
            margin-top: 60px;
            text-align: center;
            font-size: 12px;
            color: #94a3b8;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.3em;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="badge">${formula.category.name} | ${formula.difficulty}</div>
          <h1>${formula.title}</h1>
          <div class="formula-box">
            ${formula.latex}
          </div>
          
          <h2>The Core Principle</h2>
          <p>${formula.explanation}</p>
          
          ${formula.history ? `
            <h2>Historical Context</h2>
            <p>${formula.history}</p>
          ` : ''}
          
          <h2>Step-by-Step Application</h2>
          <p>${formula.example}</p>
          
          <div class="footer">
            Generated by MathematicsVerse • Premium Educational Platform
          </div>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${formula.slug}-summary.html`;
    
    setTimeout(() => {
      link.click();
      URL.revokeObjectURL(url);
      setIsDownloading(false);
      setIsCompleted(true);
      setTimeout(() => setIsCompleted(false), 3000);
    }, 800);
  };

  return (
    <button 
      onClick={handleDownload}
      disabled={isDownloading}
      className={cn(
        "w-full py-4 px-6 rounded-2xl font-black uppercase tracking-[0.15em] transition-all flex items-center justify-center space-x-3 shadow-xl text-[10px] whitespace-nowrap overflow-hidden group",
        isCompleted 
          ? "bg-green-500 text-white shadow-green-500/20" 
          : "bg-white text-black hover:bg-primary hover:text-white hover:scale-[1.02] active:scale-95 shadow-white/5"
      )}
    >
      {isDownloading ? (
        <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
      ) : isCompleted ? (
        <>
          <Check className="w-4 h-4" />
          <span>Success</span>
        </>
      ) : (
        <>
          <Download className="w-4 h-4 group-hover:animate-bounce" />
          <span>Download Summary</span>
        </>
      )}
    </button>
  );
}
